#!/usr/bin/env bash
set -euo pipefail

BASE_DIR="$( dirname "${BASH_SOURCE[0]}" )"
DIR="$(cd "${BASE_DIR}/.."; pwd)"


if [ ! -z "$(git status --porcelain --untracked=no ${DIR} ':!config')" ]; then
		echo "Working directory not clean"
		git diff -- ${DIR} ':!config' 1>&2
		exit 1
fi